# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B
template: qwen

# Data training arguments
dataset: alpaca_zh_local
cutoff_len: 1024
overwrite_cache: true

# 数据集分割：90%训练，10%验证
split: "train[:90%]"
eval_dataset: alpaca_zh_local
eval_split: "train[90%:]"

# Training arguments
stage: sft
do_train: true
do_eval: true  # 启用评估
finetuning_type: lora
lora_target: all
output_dir: ./output/alpaca_zh_with_eval
overwrite_output_dir: true

# 训练参数
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 5.0
max_steps: -1
lr_scheduler_type: cosine
warmup_ratio: 0.1

# 优化器参数
optim: adamw_torch
weight_decay: 0.01
max_grad_norm: 1.0

# 训练监控
logging_steps: 10
save_steps: 200
eval_steps: 50  # 每50步评估一次
eval_strategy: steps
eval_accumulation_steps: 1

# 精度和性能
fp16: true

# 模型保存
save_safetensors: true
load_best_model_at_end: true  # 训练结束时加载最佳模型
metric_for_best_model: eval_loss  # 根据验证损失选择最佳模型
greater_is_better: false  # 损失值越小越好
